TemplaTask/ViewModels/ContactViewModel.cs
using TemplaTask.DAL.Entities;

namespace TemplaTask.ViewModels
{
    public class ContactViewModel
    {
        public Contact Contact { get; set; }
    }
}

TemplaTask/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using TemplaTask.DAL;
using TemplaTask.ViewModels;

namespace TemplaTask.Controllers
{
    public class ContactController : Controller
    {
        private readonly AppDbContext _dbContext;

        public ContactController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var contact = _dbContext.Contact.FirstOrDefault();

            ContactViewModel viewModel = new ContactViewModel
            {
                Contact = contact,
            };

            return View(viewModel);
        }
    }
}

TemplaTask/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace TemplaTask.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TemplaTask/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TemplaTask.DAL;

namespace TemplaTask.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {

        private readonly AppDbContext _context;

        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public IViewComponentResult Invoke()
        {
            var footer = _context.Footer.Include(x => x.SocialNetworks).Include(x => x.Downloads).Include(x => x.Contacts).FirstOrDefault();

            return View(footer);
        }
    }
}

TemplaTask/Views/Contact/Index.cshtml
@using TemplaTask.ViewModels;

@{
    ContactViewModel viewModel = Model;
    var contact = viewModel.Contact;
}

<section class="section-padding" id="section_2">
    <div class="container">
        <div class="row justify-content-center">

            <div class="col-lg-5 col-12 pe-lg-5">
                <div class="contact-info">
                    <h3 class="mb-4">We love to help you. Get in touch</h3>

                    <p class="d-flex border-bottom pb-3 mb-4">
                        <strong class="d-inline me-4">Phone:</strong>
                        <span>@contact.PhoneNumber</span>
                    </p>

                    <p class="d-flex border-bottom pb-3 mb-4">
                        <strong class="d-inline me-4">Email:</strong>
                        <a href="#">@contact.Email</a>
                    </p>

                    <p class="d-flex">
                        <strong class="d-inline me-4">Location:</strong>
                        <span>@contact.Location</span>
                    </p>
                </div>
            </div>

            <div class="col-lg-5 col-12 mt-5 mt-lg-0">
                <iframe class="google-map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.819917806043!2d103.84793601429608!3d1.281807962148459!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da190c2c94ccb3%3A0x11213560829baa05!2sTwitter!5e0!3m2!1sen!2smy!4v1669212183861!5m2!1sen!2smy" width="100%" height="300" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>

        </div>
    </div>
</section>

<section class="contact-section section-padding pt-0">
    <div class="container">
        <div class="row">

            <div class="col-lg-8 col-12 mx-auto">
                <div class="section-title-wrap mb-5">
                    <h4 class="section-title">You know, Contact Form</h4>
                </div>

                <form action="#" method="post" class="custom-form contact-form" role="form">
                    <div class="row">
                        <div class="col-lg-6 col-md-6 col-12">
                            <div class="form-floating">
                                <input type="text" name="full-name" id="full-name" class="form-control" placeholder="Full Name" required="">

                                <label for="floatingInput">Full Name</label>
                            </div>
                        </div>

                        <div class="col-lg-6 col-md-6 col-12">
                            <div class="form-floating">
                                <input type="email" name="email" id="email" class="form-control" placeholder="Email address" required="">

                                <label for="floatingInput">Email address</label>
                            </div>
                        </div>

                        <div class="col-lg-12 col-12">
                            <div class="form-floating">
                                <input type="text" name="company" id="name" class="form-control" placeholder="Name" required="">

                                <label for="floatingInput">Company</label>
                            </div>

                            <div class="form-floating">
                                <textarea class="form-control" id="message" name="message" placeholder="Describe message here"></textarea>

                                <label for="floatingTextarea">Describe message here</label>
                            </div>
                        </div>

                        <div class="col-lg-4 col-12 ms-auto">
                            <button type="submit" class="form-control">Submit</button>
                        </div>

                    </div>
                </form>
            </div>

        </div>
    </div>
</section>

TemplaTask/Views/Shared/Components/Footer/Default.cshtml
@using TemplaTask.DAL.Entities;

@model Footer;

<footer class="site-footer">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 col-12 mb-5 mb-lg-0">
                <div class="subscribe-form-wrap">
                    <h6>Subscribe. Every weekly.</h6>

                    <form class="custom-form subscribe-form" action="#" method="get" role="form">
                        <input type="email" name="subscribe-email" id="subscribe-email" class="form-control" placeholder="Email Address" required="">

                        <div class="col-lg-12 col-12">
                            <button type="submit" class="form-control" id="submit">Subscribe</button>
                        </div>
                    </form>
                </div>
            </div>

            <div class="col-lg-3 col-md-6 col-12 mb-4 mb-md-0 mb-lg-0">
                <h6 class="site-footer-title mb-3">Contact</h6>

                @foreach (var item in Model.Contacts)
                {
                    <p class="mb-2"><strong class="d-inline me-2">Phone:</strong>@item.PhoneNumber </p>

                    <p>
                        <strong class="d-inline me-2">Email:</strong>
                        <a href="#">@item.Email</a>
                    </p>
                }
            </div>

            <div class="col-lg-3 col-md-6 col-12">
                <h6 class="site-footer-title mb-3">Download Mobile</h6>

                <div class="site-footer-thumb mb-4 pb-2">
                    <div class="d-flex flex-wrap">
                        @foreach (var item in Model.Downloads)
                        {
                            <a href="#">
                                <img src="~/@item.ImageUrl" class="me-3 mb-2 mb-lg-0 img-fluid" alt="">
                            </a>
                        }
                    </div>
                </div>

                <h6 class="site-footer-title mb-3">Social</h6>

                <ul class="social-icon">
                    @foreach (var item in Model.SocialNetworks)
                    {
                        <li class="social-icon-item">
                            @Html.Raw(@item.Type)
                        </li>
                    }
                </ul>
            </div>

        </div>
    </div>

    <div class="container pt-5">
        <div class="row align-items-center">

            <div class="col-lg-2 col-md-3 col-12">
                <a class="navbar-brand" href="/home/index">
                    <img src="~/images/pod-talk-logo.png" class="logo-image img-fluid" alt="templatemo pod talk">
                </a>
            </div>

            <div class="col-lg-7 col-md-9 col-12">
                <ul class="site-footer-links">
                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Homepage</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Browse episodes</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Help Center</a>
                    </li>

                    <li class="site-footer-link-item">
                        <a href="#" class="site-footer-link">Contact Us</a>
                    </li>
                </ul>
            </div>

            <div class="col-lg-3 col-12">
                <p class="copyright-text mb-0">
                    Copyright © 2036 Talk Pod Company
                    <br><br>
                    Design: <a rel="nofollow" href="https://templatemo.com/page/1" target="_parent">@Model.Designer</a>
                </p>
            </div>
        </div>
    </div>
</footer>

TemplaTask/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pod Talk - Free Bootstrap 5 CSS Template</title>

    <!-- CSS FILES -->
    <link rel="preconnect" href="https://fonts.googleapis.com">

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400&family=Sono:wght@200;300;400;500;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="~/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/css/bootstrap-icons.css">

    <link rel="stylesheet" href="~/css/owl.carousel.min.css">

    <link rel="stylesheet" href="~/css/owl.theme.default.min.css">

    <link href="~/css/templatemo-pod-talk.css" rel="stylesheet">

    <!--

    TemplateMo 584 Pod Talk

    https://templatemo.com/tm-584-pod-talk

    -->
</head>

<body>

    <main>

        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand me-lg-5 me-0" href="/home/index">
                    <img src="~/images/pod-talk-logo.png" class="logo-image img-fluid" alt="templatemo pod talk">
                </a>

                <form action="#" method="get" class="custom-form search-form flex-fill me-3" role="search">
                    <div class="input-group input-group-lg">
                        <input name="search" type="search" class="form-control" id="search" placeholder="Search Podcast" aria-label="Search">

                        <button type="submit" class="form-control" id="submit">
                            <i class="bi-search"></i>
                        </button>
                    </div>
                </form>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-lg-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="/home/index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="about.html">About</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarLightDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">Pages</a>

                            <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarLightDropdownMenuLink">
                                <li><a class="dropdown-item" href="listing-page.html">Listing Page</a></li>

                                <li><a class="dropdown-item" href="detail-page.html">Detail Page</a></li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link" href="/contact/index">Contact</a>
                        </li>
                    </ul>

                    <div class="ms-4">
                        <a href="#section_3" class="btn custom-btn custom-border-btn smoothscroll">Get started</a>
                    </div>
                </div>
            </div>
        </nav>

        @RenderBody()

    </main>

    @await Component.InvokeAsync("Footer") ;

    <!-- JAVASCRIPT FILES -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/custom.js"></script>

</body>
</html>